spring:
  datasource:
    hikari:
      validation-timeout: '3000'
      connection-timeout: '3000'
      maximum-pool-size: '5'
      max-lifetime: '240000'
      connection-test-query: SELECT NOW() FROM dual
      minimum-idle: '3'
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: ''
    username: sa
    url: jdbc:log4jdbc:h2:mem:/test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: mar31_JPA
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  thymeleaf:
    prefix: classpath:/templates/
server:
  port: '80'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
