spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3300/j25a01
    username: j25a01
    password: j25a01
  jpa:
    properties:
      hibernate: # dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: mar31_JPA
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: 'true'
server:
  port: '80'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
